import { sortBy } from 'lodash';

export const DEFAULT_YEAR = 2020;
export const PATH_BASE = "https://cors-anywhere.herokuapp.com/https://date.nager.at/api/v2/publicholidays";

export const SORTS = {
    'NONE': list => list,
    'Date': list => sortBy(list, 'date'),
    'Country Code': list => sortBy(list, 'countryCode'),
    'Local Name': list => sortBy(list, 'localName'),
    'English Name': list => sortBy(list, 'name'),
    'Launch Year': list => sortBy(list, 'launchYear'),
    'Type': list => sortBy(list, 'type'),
    'Is Global': list => sortBy(list, 'global'),
};

export const COUNTRIES = {
    'Andorra': 'AD',
    'Albania': 'AL',
    'Argentina': 'AR',
    'Austria': 'AT',
    'Australia': 'AU',
    'Åland Islands': 'AX',
    'Barbados': 'BB',
    'Belgium': 'BE',
    'Bulgaria': 'BG',
    'Benin': 'BJ',
    'Bolivia': 'BO',
    'Brazil': 'BR',
    'Bahamas': 'BS',
    'Botswana': 'BW',
    'Belarus': 'BY',
    'Belize': 'BZ',
    'Canada': 'CA',
    'Switzerland': 'CH',
    'Chile': 'CL',
    'China': 'CN',
    'Colombia': 'CO',
    'Costa Rica': 'CR',
    'Cuba': 'CU',
    'Cyprus': 'CY',
    'Czechia': 'CZ',
    'Germany': 'DE',
    'Denmark': 'DK',
    'Dominican Republic': 'DO',
    'Ecuador': 'EC',
    'Estonia': 'EE',
    'Egypt': 'EG',
    'Spain': 'ES',
    'Finland': 'FI',
    'Faroe Islands': 'FO',
    'France': 'FR',
    'Gabon': 'GA',
    'United Kingdom': 'GB',
    'Grenada': 'GD',
    'Greenland': 'GL',
    'Gambia': 'GM',
    'Greece': 'GR',
    'Guatemala': 'GT',
    'Guyana': 'GY',
    'Honduras': 'HN',
    'Croatia': 'HR',
    'Haiti': 'HT',
    'Hungary': 'HU',
    'Indonesia': 'ID',
    'Ireland': 'IE',
    'Isle of Man': 'IM',
    'Iceland': 'IS',
    'Italy': 'IT',
    'Jersey': 'JE',
    'Jamaica': 'JM',
    'Japan': 'JP',
    'Liechtenstein': 'LI',
    'Lesotho': 'LS',
    'Lithuania': 'LT',
    'Luxembourg': 'LU',
    'Latvia': 'LV',
    'Morocco': 'MA',
    'Monaco': 'MC',
    'Moldova': 'MD',
    'Madagascar': 'MG',
    'North Macedonia': 'MK',
    'Mongolia': 'MN',
    'Malta': 'MT',
    'Mexico': 'MX',
    'Mozambique': 'MZ',
    'Namibia': 'NA',
    'Niger': 'NE',
    'Nicaragua': 'NI',
    'Netherlands': 'NL',
    'Norway': 'NO',
    'New Zealand': 'NZ',
    'Panama': 'PA',
    'Peru': 'PE',
    'Poland': 'PL',
    'Puerto Rico': 'PR',
    'Portugal': 'PT',
    'Paraguay': 'PY',
    'Romania': 'RO',
    'Serbia': 'RS',
    'Russia': 'RU',
    'Sweden': 'SE',
    'Slovenia': 'SI',
    'Svalbard and Jan Mayen': 'SJ',
    'Slovakia': 'SK',
    'San Marino': 'SM',
    'Suriname': 'SR',
    'El Salvador': 'SV',
    'Tunisia': 'TN',
    'Turkey': 'TR',
    'Ukraine': 'UA',
    'United States': 'US',
    'Uruguay': 'UY',
    'Vatican City': 'VA',
    'Venezuela': 'VE',
    'Vietnam': 'VN',
    'South Africa': 'ZA',
    'Zimbabwe': 'ZW',
};

export const IMAGES = ['DE', 'GB', 'IT', 'JP', 'MD', 'NO', 'RO', 'RU', 'TR', 'US'];

export const DEFAULT_COUNTRY = 'Germany';

export const YEARS = [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026];
